 services:
   emulator:
     build: # Can change this to a prebuilt image as well
       context: .
       dockerfile: Dockerfile
       args:
         - FIREBASE_VERSION=13.3.0 # Set to latest version
     stop_grace_period: 1m
     environment:
       FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"
       FIRESTORE_EMULATOR_HOST: "localhost:8080"
       PUBSUB_EMULATOR_HOST: "localhost:8085"
       FUNCTIONS_EMULATOR_HOST: "localhost:5001"
       FIREBASE_PROJECT: "test-project" # Can be set to a real project_id or a mock one
       GCLOUD_PROJECT: "test-project" # Can be set to a real project_id or a mock one
       FORCE_COLOR: 'true'
       DATA_DIRECTORY: "data" # The directory where you will store data
       CHOKIDAR_USEPOLLING: 'true'
     healthcheck:
       test: "netstat -an | grep -c 4000"
       interval: 20s
       timeout: 20s
       retries: 10
     ports:
       - "4000:4001" # ui
       - "4400:4401" # hub
       - "4600:4601" # logging
       - "5001:5002" # functions
       - "8080:8081" # firestore
       - '8082:9081' # firestore (grpc)
       - "8085:8086" # pubsub
       - "9000:9001" # database
       - "9099:9100" # auth
       - '9229:9230' # cloud_functions_debug
       - '9199:9200' # Storage
       - '6000:6001' # Hosting
     volumes:
       - ./firebase:/srv/firebase:rw
       - ./cache:/root/.cache/:rw
       # - ~/.config/:/root/.config
       - ./firebase/data:/srv/firebase/data:rw
